; gabien-app-r48 - Editing program for various formats
; Written starting in 2016 by contributors (see CREDITS.txt)
; To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
; A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

(define-group TrAutoGen
	l28 "Region:"
	l33 "Universal String Replace"
	l34 "MEV/CEV Transcript Dump (no Troop/Item/etc.)"
	l35 "Code (or -1337 for any unknown) ?"
	l37 "Not found."
	l39 "Help"
	l40 "Configuration"
	l41 "Image Editor"
	l43 "Object Access"
	l57 "A file couldn't be read, and R48 cannot create it."
	l58 "objcompareAB.txt and objcompareBA.txt have been made."
	l60 "Wrote locmaps.txt (NOTE: You probably don't actually want to do this! Press this in RXP mode to get the CRCs, then go back to this mode to actually start editing stuff.)"
	l61 "Wrote locmaps.txt"
	l62 "The target file couldn't be read, and there's no schema to create it."
	l63 "The PRINT.txt file couldn't be read."
	l65 "Other..."
	l82 (fl2 a0 " modified. Clipboard: " a1)
	l83 "Clipboard"
	l84 "Save Clipboard To 'clip.r48'"
	l85 "Load Clipboard From 'clip.r48'"
	l86 "Inspect Clipboard"
	l88 "The clipboard was saved."
	l89 "The clipboard file is invalid or does not exist."
	l90 "The clipboard file was loaded."
	l92 "Are you sure you want to return to menu? This will lose unsaved data."
	l93 "Database Objects"
	l94 "MapInfos"
	l95 "Saves"
	l96 (fl1 "Translatables in: " a0)
	l97 "Somehow, the common events file does not have a schema."
	l98 "Unable to determine common event schema, looks like that refactor will have to happen now"
	l99 "Exported Transcript"
	l100 "To Table Of Contents"
	l101 "Table Of Contents"
	l102 "TotemSrc."
	l103 "Composite"
	l106 "Can't edit: "
	l107 "Search:"
	l108 "Add Key"
	l109 "Key "
	l110 "Parent Index. "
	l111 "<Not present - Add>"
	l112 "Manual Edit:"
	l113 "True"
	l114 "False"
	l115 "Position editor disabled."
	l116 "Can't translate ID to map."
	l117 "No such map exists."
	l118 (fl1 "Cell " a0)
	l119 "<add cell here>"
	l141 "Animation Editor"
	l142 "8px Grid"
	l143 "Import scripts/*.rb"
	l145 "Export scripts/*.rb"
	l146 "Script export complete!"
	l147 "Script name had to be adjusted: "
	l148 "Script could not be written: "
	l150 "Search"
	l151 "Search Results:"
	l152 "It appears scripts/_scripts.txt does not exist. It acts as an index."
	l153 "Script missing: "
	l154 "Import"
	l155 "Wasn't able to import 'r48.edit.txt' from the R48 settings folder."
	l156 "Export/Edit"
	l157 "Unable to start the editor! Wrote to the file 'r48.edit.txt' in the R48 settings folder."
	l158 "Wasn't able to export."
	l159 "Edit Here"
	l160 "Cannot read"
	l161 "Cannot write"
	l162 "Add to group..."
	l163 "Copy text to clipboard"
	l164 "The command isn't in the list anymore, so it has no context."
	l165 " ? "
	l166 "This command isn't known by the schema's CMDB."
	l167 "This command is known, but no description exists."
	l168 "Unknown Command"
	l169 "@indent"
	l170 "Code"
	l171 "Graphically edit this..."
	l172 "Reset Events & Version (use after map change)"
	l173 "The map's invalid, so that's not possible."
	l174 "Reset events to map state and set versioning."
	l175 "Try To Get RPG_RT To Reset The Map"
	l176 "Ok, cleaned up. If RPG_RT loads this save, the map will probably be reset."
	l177 "Default Fallback Animation"
	l178 "Death"
	l179 "Default Fallback AnimSet"
	l180 "Slime x1"
	l181 "This is basically useless without a locmaps.txt file. Please prepare one by going into RXP mode, System Tools, and pressing 'Retrieve all object strings', then return here."
	l182 "[NO DB AVAILABLE]"
	l183 "[UNKNOWN STRING. I just don't know what went wrong...]"
	toneR "R"
	toneG "G"
	toneB "B"
	toneAL "A/L"
	l188 "Incompatible clipboard and target."
	l189 "Can't copy in - copying in a range into an array requires that range be an array."
	l190 "Copying from the array interface will give you these."
	l191 "Can't copy in - the clipboard is empty."
	l192 "Cut Array"
	l193 "Add #@ #A"
	l194 "Insert Here..."
	l195 "Add Next..."
	l196 "Paste Array"
	l197 "Add..."
	l198 "Mode: Regular Array"
	l199 "Mode: Pager"
	l200 "Layer Visibility"
	l202 "Grab Tile"
	l203 "B.Copy"
	l204 "B.Paste"
	l205 "..."
	l206 (fl1 "Tile Layer " a0)
	l207 (fl2 "Tile L" a0 "(" (if a1 "'upper'/'wall' tileset flags" "general") ")")
	l208 "Passability Overlay"
	l209 "Event Layers (lower)"
	l210 "Event Layers (upper)"
	l211 "XP Tile/Event Z-Emulation Layer"
	l212 "Map Border"
	l213 "Event Selection"
	l214 "Panorama"
	l215 "RM-Style Grid Overlay"
	l216 "Event Layers"
	l217 "VXA Tile/Event Z-Emulation Layer"
	l218 "Map"
	l219 "Editing Area..."
	l220 "Click to define first point (old area shown)"
	l221 "Click again to define second point"
	l222 "Events"
	l223 "+ Add Event"
	l236 "Parent/order inconsistency error."
	l237 "Indent inconsistent for map: "
	l238 "Order inconsistency: "
	l239 "These errors must be resolved manually to use this panel."
	l240 "<Insert New Map>"
	l241 "That ID is already in use."
	l242 "Find unused ID."
	l243 "Map ID?"
	l244 "Move Out "
	l245 "Edit Info. "
	l246 "Delete"
	l247 "Root map (ID 0, type 'root) required!"
	l248 "No order for map: "
	l249 "Order contains map twice: "
	l250 "Order expects mapinfos entry: "
	l251 (fl2 a0 " : " a1)
	l252 "New..."
	l253 (fl1 a0 " (Unavailable)")
	l254 "Internal error in R48 or with file."
	l255 "Attempt Load Anyway"
	l256 " (Lowest)"
	l257 "Tiles"
	l258 "Drag to pan. Camera button: Return."
	l259 "Drag to pan. Shift-left: Pick tile. Camera button: Scroll."
	l260 "Drag to pan."
	l261 "Tap/Drag: Use tool. Camera button: Scroll."
	l262 "Shadow/Region"
	l263 "<map removed from RPG_RT.lmt>"
	l264 "The list of items in the game."
	l265 "System data (of any importance, anyway)."
	l266 "Notably, switch and variable lists have a 0th index, but only indexes starting from 1 are actually allowed to be used."
	l267 "Magic number:"
	l268 "Magic number II:"
	l269 "Load Map"
	l270 "Find Translatables"
	l271 "L0 (no Upper flag)"
	l272 "L1 (no Upper flag)"
	l273 " (Below Player)"
	l274 " (Player/Same)"
	l275 "L0 (Upper flag)"
	l276 "L1 (Upper flag)"
	l277 " (Above Player)"
)
