; gabien-app-r48 - Editing program for various formats
; Written starting in 2016 by contributors (see CREDITS.txt)
; To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
; A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

; Schema terms

(define-group TrSchema
	(enum_
		id "ID."
		int "Integer"
		sym "Symbol"
		code "Code"
	)
	(cmdb_
		unkParamName "UNK."
		defCatName "Commands"
	)
	bFileBrowser (fl1 "Browse " a0 "...")
	bOpenTable "Open Table..."
	selectTileGraphic "Select Tile Graphic..."
	(ppp_
		constant "Constant"
		idVar "From Id Var. (PPP/EasyRPG/2k3 1.12)"
		idNSfx "From Id/Name Suffix Var. Pair (PPP/EasyRPG/2k3 1.12)"
		idVarFN "idVar"
		idFN "id "
		typeFN "type "
		explain "Explain this picture mode..."
		valueVarFN "valueVar "
		isVarFN "isVar "
	)
	aElmInv "(This index isn't valid - did you modify a group from another window?)"
	aElmOpt (fl2 "Field " a0 " doesn't exist (default " a1 ")")
	l154 "Import"
	l156 "Export/Edit"
	l102 "TotemSrc."
	l103 "Composite"
	l106 "Can't edit: "
	l107 "Search:"
	l108 "Add Key"
	l109 "Key "
	l110 "Parent Index. "
	l111 "<Not present - Add>"
	l112 "Manual Edit:"
	booleanTrue "True"
	booleanFalse "False"
	l115 "Position editor disabled."
	l116 "Can't translate ID to map."
	l117 "No such map exists."
	l118 (fl1 "Cell " a0)
	l119 "<add cell here>"
	l141 "Animation Editor"
	l142 "8px Grid"
	l143 "Import scripts/*.rb"
	l145 "Export scripts/*.rb"
	l146 "Script export complete!"
	l147 "Script name had to be adjusted: "
	l148 "Script could not be written: "
	l150 "Search"
	l151 "Search Results:"
	l152 "It appears scripts/_scripts.txt does not exist. It acts as an index."
	l153 "Script missing: "
	l155 "Wasn't able to import 'r48.edit.txt' from the R48 settings folder."
	l157 "Unable to start the editor! Wrote to the file 'r48.edit.txt' in the R48 settings folder."
	l158 "Wasn't able to export."
	l159 "Edit Here"
	l160 "Cannot read"
	l161 "Cannot write"
	l162 "Add to group..."
	l163 "Copy text to clipboard"
	cmdOutOfList "The command isn't in the list anymore, so it has no context."
	cmdHelp " ? "
	cmdUnk "This command isn't known by the schema's CMDB."
	cmdNoDescription "This command is known, but no description exists."
	cmdUnkName "Unknown Command"
	theTrueNameOfAtIndent "@indent"
	codeAsInOpcode "Code"
	gpBeginButton "Graphically edit this..."
	svDoReset "Reset Events & Version (use after map change)"
	errInvalidMap "The map's invalid, so that's not possible."
	svDidTheReset "Reset events to map state and set versioning."
	svCauseReset "Try To Get RPG_RT To Reset The Map"
	svCausedTheReset "Ok, cleaned up. If RPG_RT loads this save, the map will probably be reset."
	l177 "Default Fallback Animation"
	l178 "Death"
	l179 "Default Fallback AnimSet"
	l180 "Slime x1"
	l181 "This is basically useless without a locmaps.txt file. Please prepare one by going into RXP mode, System Tools, and pressing 'Retrieve all object strings', then return here."
	l182 "[NO DB AVAILABLE]"
	l183 "[UNKNOWN STRING. I just don't know what went wrong...]"
	toneR "R"
	toneG "G"
	toneB "B"
	toneAL "A/L"
	l188 "Incompatible clipboard and target."
	l189 "Can't copy in - copying in a range into an array requires that range be an array."
	l190 "Copying from the array interface will give you these."
	l191 "Can't copy in - the clipboard is empty."
	l192 "Cut Array"
	l193 "Add #@ #A"
	l194 "Insert Here..."
	l195 "Add Next..."
	l196 "Paste Array"
	l197 "Add..."
	l198 "Mode: Regular Array"
	l199 "Mode: Pager"
)
