/*
 * gabien-app-r48 - Editing program for various formats
 * Written starting in 2016 by contributors (see CREDITS.txt)
 * To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
 * A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.
 */
package r48.tr.pages;

import r48.tr.TrPage;

/**
 * Autogenerated IDs to get the early part of the refactoring over with.
 * Created 10th March 2023.
 */
public class TrAutoGen extends TrPage {
    public String prObjectName;
    public String prSchemaID;
    public String prObjectSrc;
    public String prObjectDst;
    public String mTestFonts;
    public String mTestGraphics;
    public String mToggleFull;
    public String mSchemaTranslator;
    public String mTryRecover;
    public String mAudPlay;
    public String mREPL;
    public String warnRestoreSafety;
    public String dlgBadNum;
    public String dlgFontSize;
    public String dlgClipEmpty;
    public String mEditObj;
    public String mCorrectObj;
    public String mInspectObj;
    public String mDiffObj;
    public String mAllStr;
    public String mLoadIMI;
    public String mRMTools;
    public String mLocateEventCommand;
    public String mFindTranslatables;
    public String mRunAutoCorrect;
    public String mR48Version;

    public String l28;
    public String l33;
    public String l34;
    public String l35;
    public String l37;
    public String l39;
    public String l40;
    public String l41;
    public String l43;
    public String l57;
    public String l58;
    public String l60;
    public String l61;
    public String l62;
    public String l63;
    public String l65;
    public FF2 l82;
    public String l83;
    public String l84;
    public String l85;
    public String l86;
    public String l88;
    public String l89;
    public String l90;
    public String l92;
    public String l93;
    public String l94;
    public String l95;
    public FF1 l96;
    public String l97;
    public String l98;
    public String l99;
    public String l100;
    public String l101;
    public String l264;
    public String l265;
    public String l266;
    public String l267;
    public String l268;
    public String l269;
    public String l270;
}
