
; gabien-app-r48 - Editing program for various formats
; Written starting in 2016 by contributors (see CREDITS.txt)
; To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
; A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

(: RPG::Terms)
(+ path :.annXEncounter string= \ appeared...!)
(+ path :.preemptiveAttack string= A\ preemptive\ attack!)
(+ path :.ranAwaySafely string= Your\ escape\ succeeded.)
(+ path :.failedToEscape string= Your\ escape\ failed.)
(+ path :.wonACombat string= You\ won!)
(+ path :.partyDead string= You\ were\ defeated.)
(+ path :.experience string= experience)
(+ path :.youFound string= You\ found)
(+ path :.xMoney string= money!)
(+ path :.xReceived string= received.)
(+ path :.annXAttacksTheEnemy2KO string)
(+ path :.annCritEnemyHurt2KO string)
(+ path :.annCritPlayersHurt2KO string)
(+ path :.annXGuarding2KO string)
(+ path :.annXDoesNothing2KO string)
(+ path :.annXReadies2Attacks2KO string)
(+ path :.annXSelfDestructs2KO string)
(+ path :.annXRunsAway2KO string)
(+ path :.annXTransforms2KO string)
(+ path :.annEHurtForXHP2KO string)
(+ path :.annXMissedE2KO string)
(+ path :.annPHurtForXHP2KO string)
(+ path :.annXMissedP2KO string)
(+ path :.annXFloppedSkillA2KO string)
(+ path :.annXFloppedSkillB2KO string)
(+ path :.annXFloppedSkillC2KO string)
(+ path :.annXDodged2KO string)
(+ path :.annUsesItem2KO string)
(+ path :.annXRecovered2KO string)
(+ path :.paramInc2KO string)
(+ path :.paramDec2KO string)
(+ path :.annXHPAbsorbedFromE2KO string)
(+ path :.annXHPAbsorbedFromP2KO string)
(+ path :.resistInc2KO string)
(+ path :.resistDec2KO string)
(+ path :.levelUp string)
(+ path :.annLearnedX string)
(+ path :.battleStart string)
(+ path :.floatTxtMiss2k3 string)
(+ path :.shop1Greet string)
(+ path :.shop1Impatient string)
(+ path :.shop1Buy string= Buy)
(+ path :.shop1Sell string= Sell)
(+ path :.shop1Leave string= Leave)
(+ path :.shop1WTBQuestion string)
(+ path :.shop1ICoBQuestion string)
(+ path :.shop1Done string)
(+ path :.shop1WTSQuestion string)
(+ path :.shop1ICoSQuestion string)
(+ path :.shop1Thanks string= Thank\ you\ for\ your\ custom.)
(+ path :.shop2Greet string)
(+ path :.shop2Impatient string)
(+ path :.shop2Buy string= Buy)
(+ path :.shop2Sell string= Sell)
(+ path :.shop2Leave string= Leave)
(+ path :.shop2WTBQuestion string= How\ many?)
(+ path :.shop2ICoBQuestion string= How\ many?)
(+ path :.shop2Done string)
(+ path :.shop2WTSQuestion string)
(+ path :.shop2ICoSQuestion string)
(+ path :.shop2Thanks string= Thank\ you\ for\ your\ custom.)
(+ path :.shop3Greet string)
(+ path :.shop3Impatient string)
(+ path :.shop3Buy string= Buy)
(+ path :.shop3Sell string= Sell)
(+ path :.shop3Leave string= Leave)
(+ path :.shop3WTBQuestion string= How\ many?)
(+ path :.shop3ICoBQuestion string= How\ many?)
(+ path :.shop3Done string)
(+ path :.shop3WTSQuestion string)
(+ path :.shop3ICoSQuestion string)
(+ path :.shop3Thanks string= Thank\ you\ for\ your\ custom.)
(+ path :.inn1PriceX string= It\ costs\ )
(+ path :.inn1XGoldToSleep string= to\ sleep\ here.)
(+ path :.inn1ConfirmSleep string= Sleep?)
(+ path :.inn1SleepYes string= Sleep)
(+ path :.inn1SleepNo string= Don\'t)
(+ path :.inn2PriceX string= It\ costs\ )
(+ path :.inn2XGoldToSleep string= to\ sleep\ here.)
(+ path :.inn2ConfirmSleep string= Sleep?)
(+ path :.inn2SleepYes string= Sleep)
(+ path :.inn2SleepNo string= Don\'t)
(+ path :.headOwnedItems string= Owned)
(+ path :.headEquippedItems string= Equipped)
(+ path :.goldPostfix string= \ Gold)
(+ path :.cmdFight string= Fight)
(+ path :.cmdAuto string= Auto)
(+ path :.cmdEscape string= Escape)
(+ path :.cmdAttack2KO string= Attack)
(+ path :.cmdDefend2KO string= Defend)
(+ path :.cmdItemX string= Item)
(+ path :.cmdSkill string= Skill)
(+ path :.optEquipment string= Equipment)
(+ path :.optSave string= Save)
(+ path :.optStopGame string= Title)
(+ path :.optStart string= Begin)
(+ path :.optLoad string= Load)
(+ path :.optExitApp string= Exit)
(+ path :.menuStatus string= Status)
(+ path :.menuRow string= Row)
(+ path :.menuOrder string= Order)
(+ path :.menuWaitOn string= WaitOn)
(+ path :.menuWaitOff string= WaitOff)
(+ path :.batStatLevel string= Level)
(+ path :.batStatHP string= HP)
(+ path :.batStatSP string= SP)
(+ path :.batStatNoStateFx string= No.StateFx)
(+ path :.exp2ch string= XP)
(+ path :.lvl2ch string= Lv)
(+ path :.hp2ch string= HP)
(+ path :.sp2ch string= SP)
(+ path :.spCost string= Sp.Cost)
(+ path :.statAtk string= ATK)
(+ path :.statDef string= DEF)
(+ path :.statSpi string= SPI)
(+ path :.statAgi string= AGI)
(+ path :.equipWeapon string= Weapon)
(+ path :.equipShield string= Shield)
(+ path :.equipArmour string= Armour)
(+ path :.equipHelmet string= Helmet)
(+ path :.equipAccessory string= Accessory)
(+ path :.saveSlot string= Save...)
(+ path :.loadSlot string= Load...)
(+ path :.file string= File)
(+ path :.exitGame string= Exit?)
(+ path :.yes string= Yes)
(+ path :.no string= No)
(+ optP :.easyrpgItemNumberSeparator string)
(+ optP :.easyrpgSkillCostSeparator string)
(+ optP :.easyrpgEquipmentArrow string)
(+ optP :.easyrpgStatusSceneName string)
(+ optP :.easyrpgStatusSceneClass string)
(+ optP :.easyrpgStatusSceneTitle string)
(+ optP :.easyrpgStatusSceneCondition string)
(+ optP :.easyrpgStatusSceneFront string)
(+ optP :.easyrpgStatusSceneBack string)
(+ optP :.easyrpgOrderSceneConfirm string)
(+ optP :.easyrpgOrderSceneRedo string)
(+ optP :.easyrpgAnnBattleDoubleAttack2k3 string)
(+ optP :.easyrpgAnnBattleDefend2k3 string)
(+ optP :.easyrpgAnnBattleObserve2k3 string)
(+ optP :.easyrpgAnnBattleCharge2k3 string)
(+ optP :.easyrpgAnnBattleSelfdestruct2k3 string)
(+ optP :.easyrpgAnnBattleEscape2k3 string)
(+ optP :.easyrpgAnnBattleSpecialCombatBack2k3 string)
(+ optP :.easyrpgAnnBattleSkill2k3 string)
(+ optP :.easyrpgAnnBattleItem2k3 string)
