
; gabien-app-r48 - Editing program for various formats
; Written starting in 2016 by contributors (see CREDITS.txt)
; To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
; A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

; VX Ace Enemy Battle Actions Helpfile
; "The Bat Theme Continues" (this is the 3rd Batfile)

(obj 0 "None")
(.)
(. No condition applies!)
(. For lack of a better place, I\'ll explain the rating system here, to my understanding.)
(. Imagine there is a line, with the rating of highest *valid* rated action at the top, and that number minus \3 at the bottom.)
(. For rating purposes, the highest rating minus \3 is considered \0, so the variance is between \0 \(max minus \3\) and \3 \(max\).)
(. Furthermore, all actions with a rating <= \0 are culled early.)
(. So, to force an action, it would simply have to have a rating \3 more than any other action.)
(. This is important if you want an action to always be performed under certain conditions without a random chance of anything else.)
(.)
(. @param1: Useless.)
(. @param2: Also useless.)
(.)

(obj 1 "Turns Passed")
(.)
(. If @param2 is \0, this is simple:)
(. On turn @param1, run this action.)
(.)
(. If @param2 isn\'t \0, this becomes more complicated.)
(. Essentially, the battle is divided into blocks of @param2 turns.)
(. @param1 should be between \0 and \(@param2 \- \1\).)
(. Also, this will never happen if the turn count is \0.)
(.)
(. @param1: Turn number.)
(. @param2: Turn block size \(or \0 for this to only happen once\))
(.)

(obj 2 "HP Check")
(.)
(. This checks if the HP, divided by the max HP, is between param1 and param2.)
(. Note that they should be decimals \(\'f\'\) between \0.0 and \1.0.)
(.)
(. @param1: Lower bound)
(. @param2: Upper bound)
(.)

(obj 3 "MP Check")
(.)
(. This checks if the MP, divided by the max MP, is between param1 and param2.)
(. Note that they should be decimals between \0.0 and \1.0.)
(.)
(. @param1: Lower bound)
(. @param2: Upper bound)
(.)

(obj 4 "State Check")
(.)
(. This checks if the enemy has a given state.)
(.)
(. @param1: State ID.)
(. @param2: No meaning.)
(.)

(obj 5 "Highest level in party is >=...")
(.)
(. This checks if the player\'s party has any members above a level.)
(.)
(. @param1: Level.)
(. @param2: No meaning.)
(.)

(obj 6 "Switch On")
(.)
(. This checks if a switch is on.)
(.)
(. @param1: Switch ID)
(. @param2: No meaning.)
(.)
